server: 
  port: 3344 
  
spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shilohchencz/springcloud-config.git #GitHub上面的git仓库名字


